title: Ari Cacic # your name (or website title) here
logo: "/images/IMG_1954.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. Environmental Science and Geography, GIS Certificate
  <br><br>
  UMBC 2021 
  <br><br>
  <a href="https://www.linkedin.com/in/arianna-cacic-34012a181">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
