title: Ari Cacic # your name (or website title) here
logo: "/images/IMG_1954.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC Class of 2021, B.S. Environmental Science and Geography, GIS Certificate. NOAA Ernest F. Hollings Undergraduate Scholarship Recipient. UMBC Sondheim Public Affairs Scholar, Cohort 19. 
  <br><br>
  Research experience with UMBC's GES and Interdisciplinary Departments. Lab Proctor/TA for the GES Department. Former intern at the Maryland General Assembly with the Environment and Transportation Committee. 
  <br><br>
  <a href="https://www.linkedin.com/in/arianna-cacic-34012a181">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
